model_name: thick_rn

# 0 -- AutoDecoder (AD), 1 -- ReconNet (RN)
task_type: 1
use_thick_slices: True

batch_size_train: 4
batch_size_val: 4

num_epochs: 80
log_epoch_count: 1
checkpoint_epoch_count: 5
